
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzczytoqldivhexwakal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6Y3p5dG9xbGRpdmhleHdha2FsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNDE5NTYsImV4cCI6MjA2MTcxNzk1Nn0.4UcYdDXGKJG6zd_ptWRuTHhv4F5r46k-Z4bUdfT6LUc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
